Models/Camiones.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trasportes_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camiones
    {
        public int ID_Camion { get; set; }
        public string Matricula { get; set; }
        public string Tipo_Camion { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Capacidad { get; set; }
        public double Kilometraje { get; set; }
        public string UrlFoto { get; set; }
        public bool Disponibilidad { get; set; }
    }
}

Controllers/CamionesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DTO;
using Microsoft.Ajax.Utilities;
using Trasportes_MVC.Models;

namespace Trasportes_MVC.Controllers
{
    public class CamionesController : Controller
    {
        // GET: Camiones
        public ActionResult Index()
        {
            //Crear la lista de camiones del modelo original
            List<Camiones> lista_camiones = new List<Camiones>();
            //lleno la lista con elelemntos existentes dentro dle contexto (BD) ustoilizando EF y LinQ
            using (TransportesEntities context = new TransportesEntities())
            {
                //lleno mi loista directamente usando LinQ
                //consulta directa
                //lista_camiones = (from camion in context.Camiones select camion).ToList();
                //otra forma de usar LinQ=
                lista_camiones = context.Camiones.ToList();
                //otra forma de hacerlo
                //foreach(Camiones cam in context.Camiones)
                //{
                //  lista_camiones.Add(cam);
                //}
            }
            //ViewBang (forma parte de razor) se caracteriza por hacer uso de una propiedad arbitraria que sirve para pasar informacion desde el controlador a la vista 
            ViewBag.Titulo = "Lista de camiones";
            ViewBag.Subtitulo = "Utilizando ASP.NET MVC";

            //ViewData se caracteriza por ahacer uso de un atributo arbitrario y tiene el mismo funcionamiento que el ViewBag
            ViewData["Titulo2"] = "Segundo Titulo";

            //TempData se caracteriza por permitir crear variables temporales que existen dutante la ejecucion del Runtime de ASP
            //ademas , los temdata me permiten compartir informacion no soslo del controlador a la vista, sino tambien entre otras vistas y otros controladores 
            //TempData.Add("Clave", "Valor");

            //retorno la vista con los datos del modelo 
            return View(lista_camiones);
        }

        //GET: Nuevo_Camion
        public ActionResult Nuevo_Camion()
        {
            ViewBag.Titulo = "Nuevo camion";
            cargarDDL();
            return View();
        }

        //POST:Nuevo_Camion
        [HttpPost]
        public ActionResult Nuevo_Camion(Camiones_DTO model, HttpPostedFileBase imagen)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (TransportesEntities context = new TransportesEntities())
                    {
                        var camion = new Camiones();//creo una instancia de un objeto del modelo original (<PROYECTO>.Models)
                        //asignar todos los valores de modelo d entrada (DTO) al otro objetop que sera enviado a la BD
                        camion.Matricula = model.Matricula;
                        camion.Marca = model.Marca;
                        camion.Modelo = model.Modelo;
                        camion.Tipo_Camion = model.Tipo_Camion;
                        camion.Capacidad = model.Capacidad;
                        camion.Kilometraje = model.Kilometraje;
                        camion.Disponibilidad = model.Disponibilidad;
                        //validamos si existe una imagen en la peticion 
                        if (imagen != null && imagen.ContentLength > 0)
                        {
                            string filename = Path.GetFileName(imagen.FileName);//recupero el nombre la imagen que viene de la peticion
                            string pathdir = Server.MapPath("~/Assets/Imagenes/Camiones/");//mapeo la ruta donde guardare mi imagen en el servidor
                            if (!Directory.Exists(pathdir))//sino existe el directorio, lo creo{
                            {
                                Directory.CreateDirectory(pathdir);
                            }
                            imagen.SaveAs(pathdir + filename);//guardo la imagen en el servidor
                            camion.UrlFoto = "/Assets/Imagenes/Camiones/" + filename;//guardo la ruta y el nombre del archivo para enviarla a la BD

                            //Impacto sobre la BD usando EF
                            context.Camiones.Add(camion);//agregar un nuevo camion al contexto 
                            context.SaveChanges();//inpacto la base de datos enviando las notificaciones sufridas en el contexto

                            return RedirectToAction("Index");//finalmente, regreso al listado de este mismo controlador (Camiones ) si es que todo salio bien.
                        }
                        else
                        {
                            cargarDDL();
                            return View(model);
                        }
                    }
                }
                else
                {
                    cargarDDL();
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                //en caso de que ocurra una exepcion, voy a mostrar un msj con el error(SweetAlert), voy a devolver la vista del modeo que causo elmconflicto (return View(model)) y vuelvona cargar el DDL que esten disponibles esas opciones 
                cargarDDL();
                return View();
            }
        }

        //GET: Editar_camion/{id}
        public ActionResult Editar_Camion(int id)
        {
            if (id > 0)
            {
                Camiones_DTO camion = new Camiones_DTO(); //creo una instancia del tipo DTO para pasar informacion desde el contexto a la vista en ayuda de EF y LinQ
                using (TransportesEntities context = new TransportesEntities())
                {
                    //busco a aquel elemento que coincida con el ID
                    //Bajo metodo
                    //No puedo 
                    var camion_aux = context.Camiones.Where(x => x.ID_Camion == id).FirstOrDefault();
                    var camion_aux2 = context.Camiones.FirstOrDefault(x => x.ID_Camion == id);

                    camion.Matricula = camion_aux.Matricula;
                    camion.Marca = camion_aux.Marca;
                    camion.Modelo = camion_aux.Modelo;
                    camion.Capacidad = camion_aux.Capacidad;
                    camion.Kilometraje = camion_aux.Kilometraje;
                    camion.Tipo_Camion = camion_aux.Tipo_Camion;
                    camion.Disponibilidad = camion_aux.Disponibilidad;
                    camion.UrlFoto = camion_aux.UrlFoto;
                    camion.ID_Camion = camion_aux.ID_Camion;

                    //bajo una consulta (usando LinQ)
                    //cuando hago una consulta directa , tengo la oportunodad de asignar valores a tipo de datos mas complejos o diferentes, incluso, pudiendo crear nuevos datos a partir de dtos existentes 
                    camion = (from c in context.Camiones
                              where c.ID_Camion == id
                              select new Camiones_DTO()
                              {
                                  ID_Camion = c.ID_Camion,
                                  Matricula = c.Matricula,
                                  Marca = c.Marca,
                                  Modelo = c.Modelo,
                                  Capacidad = c.Capacidad,
                                  Kilometraje = c.Kilometraje,
                                  Tipo_Camion = c.Tipo_Camion,
                                  Disponibilidad = c.Disponibilidad,
                                  UrlFoto = c.UrlFoto
                              }).FirstOrDefault();
                }//cierre el Using(context)
                if (camion == null)//valido si realmente recupere los datos de la base de dtos {
                {
                    return RedirectToAction("Index");
                }
                ViewBag.Titulo = $"Editar Camion °{camion.ID_Camion}";
                cargarDDL();
                return View(camion);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        //POST: Editar_Camion
        //POST: Editar_Camion
        [HttpPost]
        public ActionResult Editar_Camion(Camiones_DTO model, HttpPostedFileBase imagen)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (TransportesEntities context = new TransportesEntities())
                    {
                        var camion = new Camiones();

                        camion.ID_Camion = model.ID_Camion;
                        camion.Matricula = model.Matricula;
                        camion.Marca = model.Marca;
                        camion.Modelo = model.Modelo;
                        camion.Capacidad = model.Capacidad;
                        camion.Tipo_Camion = model.Tipo_Camion;
                        camion.Disponibilidad = model.Disponibilidad;
                        camion.Kilometraje = model.Kilometraje;

                        if (imagen != null && imagen.ContentLength > 0)
                        {
                            string filename = Path.GetFileName(imagen.FileName);
                            string pathdir = Server.MapPath("~/Assets/Imagenes/Camiones/");
                            if (model.UrlFoto.Length == 0)
                            {
                                //la imagen en la BD es null y hay que darle la imagen
                                if (!Directory.Exists(pathdir))
                                {
                                    Directory.CreateDirectory(pathdir);
                                }

                                imagen.SaveAs(pathdir + filename);

Views/Camiones/Editar_Camion.cshtml
@model DTO.Camiones_DTO
@*Indicamos a Razor que utilizaremos un modelo especificos*@


<h2>@ViewBag.Titulo</h2>
@*comenczamos a crear nuestro formulario
    HTML HELPER BeginForm es el HTML Helper*@

@using (Html.BeginForm("Editar_Camion", "Camiones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-12">

            @*Recuperar y  enviar la informacion NO EDITABLE en el 2do plano 
            esta informacion no se muestra en el formulario, pero es requisito para nuestro modelo*@
            @Html.HiddenFor(model=> model.UrlFoto)
            @Html.HiddenFor(model=>model.ID_Camion)


            <div>
                @*generamos la etiqueta label*@
                @Html.LabelFor(model => model.Matricula)
                @*generamos la etiqueta input*@
                @Html.TextBoxFor(model => model.Matricula, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para le msg de validacion*@
                @Html.ValidationMessageFor(model => model.Matricula, null)
            </div>

            <div>
                @*generamos la etiqueta label*@
                @Html.LabelFor(model => model.Capacidad)
                @*generamos la etiqueta input*@
                @Html.TextBoxFor(model => model.Capacidad, new { @class = "form-control", @type = "number" })
                @*generamos un espacio para le msg de validacion*@
                @Html.ValidationMessageFor(model => model.Capacidad, null)
            </div>

            <div>
                @*generamos la etiqueta label*@
                @Html.LabelFor(model => model.Marca)
                @*generamos la etiqueta input*@
                @Html.TextBoxFor(model => model.Marca, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para le msg de validacion*@
                @Html.ValidationMessageFor(model => model.Marca, null)
            </div>

            <div>
                @*generamos la etiqueta label*@
                @Html.LabelFor(model => model.Modelo)
                @*generamos la etiqueta input*@
                @Html.TextBoxFor(model => model.Modelo, new { @class = "form-control", @type = "text" })
                @*generamos un espacio para le msg de validacion*@
                @Html.ValidationMessageFor(model => model.Modelo, null)
            </div>

            <div>
                @*generamos la etiqueta label*@
                @Html.LabelFor(model => model.Kilometraje)
                @*generamos la etiqueta input*@
                @Html.TextBoxFor(model => model.Kilometraje, new { @class = "form-control", @type = "number" })
                @*generamos un espacio para le msg de validacion*@
                @Html.ValidationMessageFor(model => model.Kilometraje, null)
            </div>

            <div>
                @*generamos la etiqueta label*@
                @Html.LabelFor(model => model.Disponibilidad)
                @Html.CheckBoxFor(model => model.Disponibilidad)
            </div>
            @*DDL TIPO DE CAMION*@
            <div>
                @Html.LabelFor(model => model.Tipo_Camion)
                @Html.DropDownListFor(model => model.Tipo_Camion, new SelectList(ViewBag.ListaTipos, "Descripcion", "Descripcion"), new { @class = "form-control" })
            </div>

            <div>
                @Html.LabelFor(model => model.UrlFoto)
                <input type="file" name="imagen" id="imagen" />
            </div>

            <div style="text-align: right;">
                <input value="Guardar" class="btn btn-success" type="submit" />
            </div>


        </div>
    </div>
}

Views/Camiones/Index.cshtml
@*recupero el viewBag*@

@*para referenciar un metodo, una variable o un elemento de codigo utilizado '@'*@

<h1>@ViewBag.Titulo</h1>
<h1>@ViewBag.Subtitulo</h1>

@*creo una tabla´para mostrar mis camiones*@
@*<table class="table table-bordered table-striped table-striped-columns table-responsive">*@
@*<thead>
            <tr>
                <th scope="col"> ID_Camion     </th>
                <th scope="col"> Matricula     </th>
                <th scope="col"> Tipo_Camion   </th>
                <th scope="col"> Marca         </th>
                <th scope="col"> Modelo        </th>
                <th scope="col"> Capacidad     </th>
                <th scope="col"> Kilometraje   </th>
                <th scope="col"> UrlFoto       </th>
                <th scope="col"> Disponibilidad</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var camion in Model)
            {
                <tr>
                    <td>@camion.ID_Camion </td>
                    <td>@camion.Matricula </td>
                    <td>@camion.Tipo_Camion </td>
                    <td>@camion.Marca </td>
                    <td>@camion.Modelo </td>
                    <td>@camion.Capacidad </td>
                    <td>@camion.Kilometraje </td>
                    <td>@camion.UrlFoto </td>
                    <td>@camion.Disponibilidad </td>
                </tr>

            }
        </tbody>
    </table>*@

<div class="row">
    <div class="col-md-2" style="text-align:right;">
        <a href="~/Camiones/Nuevo_camion" class="btn btn-primary">Nuevo camion</a>
    </div>
</div>

<div class="col-md-12  row text-center">
    @foreach (var camion in Model)
    {
        <div class="col-md-3 col-sm-12">
            @*//Tarjeta de Bootstrap*@
            <div class="card" style="width: 18rem;">
                <img src="@camion.UrlFoto" class="card-img-top" alt="@camion.UrlFoto">
                <div class="card-body">
                    <h2 class="card-title">Camion no. @camion.ID_Camion</h2>
                    <h5 class="card-title">@camion.Matricula</h5>
                    <ul>
                        <li class="card-text">@camion.Capacidad</li>
                        <li class="card-text">@camion.Tipo_Camion</li>
                        <li class="card-text">@camion.Marca</li>
                        <li class="card-text">@camion.Modelo</li>
                        <li class="card-text">@camion.Kilometraje</li>
                        <li class="card-text">@camion.Disponibilidad</li>
                    </ul>
                    <a class="btn btn-warning" href="~/Camiones/Editar_Camion/@camion.ID_Camion">Editar</a>
                    <a class="btn btn-danger" href="~/Camiones/Confirmar_Eliminar/@camion.ID_Camion">Eliminar</a>
                </div>
            </div>
        </div>
    }
</div>

Views/Camiones/Nuevo_Camion.cshtml
@model DTO.Camiones_DTO
@*Indicamos a Razor que utilizaremos un modelo especificos*@


<h2>@ViewBag.Titulo</h2>
@*comenczamos a crear nuestro formulario
HTML HELPER BeginForm es el HTML Helper*@ 

@using(Html.BeginForm("Nuevo_Camion", "Camiones", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <div class="col-12">
                        <div>
                            @*generamos la etiqueta label*@
                            @Html.LabelFor(model => model.Matricula)
                            @*generamos la etiqueta input*@
                            @Html.TextBoxFor(model => model.Matricula, new { @class = "form-control", @type = "text" })
                            @*generamos un espacio para le msg de validacion*@
                            @Html.ValidationMessageFor(model => model.Matricula, null)
                        </div>

                        <div>
                            @*generamos la etiqueta label*@
                            @Html.LabelFor(model => model.Capacidad)
                            @*generamos la etiqueta input*@
                            @Html.TextBoxFor(model => model.Capacidad, new { @class = "form-control", @type = "number" })
                            @*generamos un espacio para le msg de validacion*@
                            @Html.ValidationMessageFor(model => model.Capacidad, null)
                        </div>

                        <div>
                            @*generamos la etiqueta label*@
                            @Html.LabelFor(model => model.Marca)
                            @*generamos la etiqueta input*@
                            @Html.TextBoxFor(model => model.Marca, new { @class = "form-control", @type = "text" })
                            @*generamos un espacio para le msg de validacion*@
                            @Html.ValidationMessageFor(model => model.Marca, null)
                        </div>

                        <div>
                            @*generamos la etiqueta label*@
                            @Html.LabelFor(model => model.Modelo)
                            @*generamos la etiqueta input*@
                            @Html.TextBoxFor(model => model.Modelo, new { @class = "form-control", @type = "text" })
                            @*generamos un espacio para le msg de validacion*@
                            @Html.ValidationMessageFor(model => model.Modelo, null)
                        </div>

                        <div>
                            @*generamos la etiqueta label*@
                            @Html.LabelFor(model => model.Kilometraje)
                            @*generamos la etiqueta input*@
                            @Html.TextBoxFor(model => model.Kilometraje, new { @class = "form-control", @type = "number" })
                            @*generamos un espacio para le msg de validacion*@
                            @Html.ValidationMessageFor(model => model.Kilometraje, null)
                        </div>

                        <div>
                            @*generamos la etiqueta label*@
                            @Html.LabelFor(model => model.Disponibilidad)
                            @Html.CheckBoxFor(model => model.Disponibilidad)
                        </div>
                        @*DDL TIPO DE CAMION*@
                        <div>
                            @Html.LabelFor(model=>model.Tipo_Camion)
                            @Html.DropDownListFor(model=>model.Tipo_Camion, new SelectList(ViewBag.ListaTipos, "Descripcion", "Descripcion"), new { @class = "form-control" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.UrlFoto)
                            <input type="file" name="imagen" id="imagen"/>
                        </div>

                        <div style="text-align: right;">
                            <input value="Guardar" class="btn btn-success" type="submit" />
                        </div>


                    </div>
                </div>
            }